artConnection.demoOrderManagement.demoOrderManagement.jdbc.orders_postgres.connectionEnabled=true
artConnection.demoOrderManagement.demoOrderManagement.jdbc.orders_postgres.connectionSettings.serverName=$env{DB_SERVER_NAME}
artConnection.demoOrderManagement.demoOrderManagement.jdbc.orders_postgres.connectionSettings.portNumber=$env{DB_PORT}
artConnection.demoOrderManagement.demoOrderManagement.jdbc.orders_postgres.connectionSettings.databaseName=$env{DB_DATABASE_NAME}
artConnection.demoOrderManagement.demoOrderManagement.jdbc.orders_postgres.connectionSettings.user=$env{DB_USERNAME}
artConnection.demoOrderManagement.demoOrderManagement.jdbc.orders_postgres.connectionSettings.password=$env{DB_PASSWORD}

jndi.DEFAULT_IS_JNDI_PROVIDER.providerURL=$env{JNDI_URL}
jms.DEFAULT_IS_JMS_CONNECTION.clientID=DEFAULT_IS_JMS_CLIENT
jms.DEFAULT_IS_JMS_CONNECTION.enabled=true
jms.DEFAULT_IS_JMS_CONNECTION.csqSize=0
jms.DEFAULT_IS_JMS_CONNECTION.jndi_jndiAliasName=DEFAULT_IS_JNDI_PROVIDER
jms.DEFAULT_IS_JMS_CONNECTION.jndi_automaticallyCreateUMAdminObjects=true
jms.DEFAULT_IS_JMS_CONNECTION.producerMaxRetryAttempts=30
jms.DEFAULT_IS_JMS_CONNECTION.producerRetryInterval=1000
jms.DEFAULT_IS_JMS_CONNECTION.jndi_connectionFactoryLookupName=docker_um

keystore.API_KEYSTORE.ksLocation=/certs/api_keystore.p12
keystore.API_KEYSTORE.ksType=PKCS12
keystore.API_KEYSTORE.ksStoreProviderName=SUN
keystore.API_KEYSTORE.ksPassword=$env{API_KEYSTORE_PASSWORD}
keystore.API_KEYSTORE.keyAlias.sttlab.local.keyAliasPassword=$env{API_KEYSTORE_PASSWORD}


settings.watt.net.default.accept=application/json
settings.watt.server.ns.lockingMode=none

user.Administrator.password=$env{ADMIN_PASSWORD}

group.Everybody.users=tester
user.tester.password=$env{TESTER_PASSWORD}