services:
  # msr: 
  #   image: ibmwebmethods.azurecr.io/webmethods-microservicesruntime:11.1.0.9
  #   container_name: ${DEPLOYMENT_NAME}
  #   networks:
  #     - wm
  #   ports:
  #     - "${MSR_DEV_PORT_NUMBER}:5555"
  #   volumes:
  #     - msr_dev_config:/opt/softwareag/IntegrationServer/config
  #     - msr_dev_packages:/opt/softwareag/IntegrationServer/packages
  #     - $HOME/git:/git  # Mounting the host's git directory to easily copy files in/out of the container for development purposes. Adjust as needed.
  #   env_file:
  #     - .env
  #   healthcheck:
  #     interval: 5s
  #     retries: 24
  #     test: ["CMD-SHELL", "curl -o /dev/null -s -w '%{http_code}' http://localhost:5555 | grep -qE '^(200|3[0-9]{2})$'"]

  postgres:
    image: postgres:latest
    container_name: postgres-dev
    networks:
      - wm
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres-vol:/var/lib/postgresql/data

  umserver:
    image: ibmwebmethods.azurecr.io/universalmessaging-server:11.1.2
    container_name: umserver-dev
    networks:
      - wm
    ports:
      - "9000:9000"
      - "9200:9200"
    env_file:
      - .env
    volumes:
      - um-data-vol:/opt/softwareag/UniversalMessaging/server/umserver/data
      - um-conf-vol:/opt/softwareag/common/conf
    healthcheck:
      interval: 5s
      retries: 12
      test: ["CMD-SHELL", "curl --silent http://localhost:9000/health/ | grep -q '\"ServerStatus\":\"OK\"'"]

networks:
  wm:

volumes:
  msr_dev_config:
  msr_dev_packages:
  postgres-vol:
  um-data-vol:
  um-conf-vol: