apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: msr-order-management
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ocs-external-storagecluster-cephfs
